{
    "name": "CRM Stage Probability Automation",
    "depends": ["base", 'crm'],
    "category": "CRM",
    "version": '18.0.1.0.0',
    'author': 'The Lange Companies',
    "data": [
        # "security/ir.model.access.csv",
        # "security/security.xml",
        # "views/tier_menu_views.xml",
        # "views/commission_plan_views.xml",
        # "views/crm_lead_views.xml",
        # "views/eo_insurance_tier_views.xml",
        # "views/res_config_settings_views.xml",
        # "views/res_partner_views.xml",
        # "views/res_user_views.xml",
        # "report/commission_report.xml",
        "data/crm_stage_automation.xml",
    ],
    "license": "LGPL-3",
    "summary": "Lange Real Estate (RE) Residential and Commercial Commissions",
    "application": False,
    "installable": True,
}
