from odoo import fields, models


class ResPartner(models.Model):
    _inherit = 'res.partner'

    contact_owner_id = fields.Many2one('res.users', 'Contact Owner',
                                       help='Related Owner of Contact')
    zoho_record_id = fields.Char('Zoho Contact Reference', help='Record reference in Zoho')
    home_phone = fields.Char('Home phone', help='Home Phone')
    other_phone = fields.Char('Other phone', help='Other Phone')
    birth_date = fields.Date(string='Date of Birth of zoho Contact',
                             help='Date of Birth of Contacts')
    assistant = fields.Char('Assistant', help='Contact Assistant')
    mailing_street = fields.Char('Mailing Street',
                                 help='Mailing Street of Contact')
    other_street = fields.Char('Other Street', help='Other Street of Contact')
    mailing_city = fields.Char('Mailing City', help='Mailing City of Contact')
    other_city = fields.Char('Other City', help='Other City of Contact')
    mailing_state_id = fields.Many2one('res.country.state', 'Mailing State',
                                    help='Mailing state of Contact')
    other_state_id = fields.Many2one('res.country.state', 'Other State',
                                  help='Other state of Contact')
    mailing_zip = fields.Char('Mailing Zip', help='Mailing Zip of Contact')
    other_zip = fields.Char('Other Zip', help='Other Zip of Contact')
    mailing_country_id = fields.Many2one('res.country',
                                      help='Mailing country of Contact')
    other_country_id = fields.Many2one('res.country',
                                    help='Other country of Contact')
    description = fields.Char('Description', help='Zoho description of Contact')
    salutation = fields.Char('Salutation', help='Salutation of Contact')
    secondary_email = fields.Char('Secondary Email',
                                  help='Secondary Email of Contatct')
    tag = fields.Char(string='Tag', help='Contact Tag')
    residence_zip = fields.Char(string='Residence Zip',
                                help='Residance Zip of Contact')
    notes = fields.Char(string='Zoho Notes', help='Notes')
    subject = fields.Char('Subject', help='Subject')
    business_type = fields.Char('Type of Business', help='Type of Business')
    bussiness_state_id = fields.Many2one('res.country.state',
                                      string='State of Business Registration')
    fien_number = fields.Char('Federal Employer Identification Number (FIEN)',
                              help='Federal Employer Identification Number (FIEN)')
    bussiness_street_address = fields.Char('Business Street Address',
                                           help='Business Street Address')
    time_in_business = fields.Char('Time in Business', help='Time in Business')
    industry_experience = fields.Float('Industry Experience (years)',
                                       help='Industry Experience (years)')
    annual_revanue = fields.Char('Annual Revenue', help='Annual Revenue')
    employee_count = fields.Char('Number of Employees',
                                 help='Number of Employees')
    owner_legal_name = fields.Char("Guarantor/Owner's Full Legal Name",
                                   help="Guarantor/Owner's Full Legal Name")
    social_security_number = fields.Char('Social Security Number')
    residence_address = fields.Char('Residence Address')
    residance_state_id = fields.Many2one('res.country.state', 'Residence State')
    residance_city = fields.Char('Residence City')
    business_zip = fields.Char('Business zip')
    equipment_description = fields.Char('Equipment Description')
    equipment_cost = fields.Char('Equipment Cost')
    equipment_dealer = fields.Char('Equipment Dealer')
    equipment_dealer_contact = fields.Char('Equipment Dealer Contact')
    equipment_dealer_phone = fields.Char('Equipment Dealer Phone')
    preferred_name = fields.Char('Preferred Name')
    industry = fields.Char('Industry Drop Down')
    account_owner_id = fields.Many2one('res.users', string='Account Owner',
                                       help="Related Account Owner of Contact")
    account_site = fields.Char('Account Site', help="Account Site of Contact")
    fax = fields.Char('Fax', help="fax")
    account_type = fields.Char('Account Type', help="Account Type")
    ownership = fields.Char('Ownership', help="Ownership")
    sic_code = fields.Char('SIC Code', help="SIC Code")
    billing_street = fields.Char('Billing Street', help="Billing Street")
    shipping_street = fields.Char('Shipping Street', help="Shipping Street")
    billing_city = fields.Char('Billing City', help="Billing City")
    shipping_city = fields.Char('Shipping City', help="Shipping City")
    billing_state_id = fields.Many2one('res.country.state', 'Billing State')
    shipping_state_id = fields.Many2one('res.country.state', 'Shipping State')
    billing_code =  fields.Char('Billing Code', help="Billing Code")
    shipping_code =  fields.Char('Shipping Code', help="Shipping Code")
    billing_country_id = fields.Many2one('res.country',help='Billing country of Contact')
    shipping_country_id = fields.Many2one('res.country',help='Shipping country of Contact')
    physical_address = fields.Char('Physical Address', help='Physical Address of Contact')
    physical_city = fields.Char('Physical City', help='Physical City')
    physical_state_id = fields.Many2one('res.country.state', 'Physical State')
    physical_zip = fields.Char('Physical Zip', help='Physical Zip of Contact')
    company_legal_name = fields.Char('Company Legal name', help='Legal name of company of contact')
    purchase_plan = fields.Char('When do you plan to purchase?', help='Purchase plan of the contact')
    hear_about_us = fields.Char("How Did You Hear About Us?",help="How Did You Hear About Us?")
    intrested_product = fields.Char('Which product(s) are you interested in?',help="Which product(s) are you interested in?")
    sales_notes = fields.Char('Sales Notes', help='Sales notes')
    product_family = fields.Char('Product Family', help="Product Family")
    do_not_mail = fields.Char('Do Not Mail', help="Do Not Mail")
    company_type = fields.Char('Company Type', help='Company Type')
    sales_rep = fields.Char('Sales Rep', help='Sales Rep')
    outcome = fields.Char('OutCome', help='Outcome')
    online_date = fields.Date('On-line date',help='On-line Date')
    offline_date = fields.Date('Offline Date', help='Offline Date')
    install_week = fields.Date('Install Week', help='Install Week')
    storage_location = fields.Char('Storage Location', help='Storage Location of Contacts')
    sale_date = fields.Date('Sale Date', help='Sale Date')
    serial_number = fields.Char('Serial number', help='Serial number')
    ship_date = fields.Date('Ship Date',help='Ship Date')
    nssa = fields.Char('NSSA', help='NSSA of the contact')
    customer_service_note = fields.Char('Customer service notes', help='Customer service notes')
    delivery_method = fields.Char('Delivery Method', help='Delivery method of customer in zoho')
    wellness_contact_1 = fields.Char('Wellness contact 1', help='First Wellness Address of contact')
    wellness_contact_2 = fields.Char('Wellness contact 2', help='Second Wellness Address of contact')
    wellness_contact_3 = fields.Char('Wellness contact 3', help='Third Wellness Address of contact')
    wellness_phone_1 = fields.Char('Wellness Phone 1',
                                     help='First Wellness phone of contact')
    wellness_phone_2 = fields.Char('Wellness Phone 2',
                                   help='Second Wellness phone of contact')
    wellness_phone_3 = fields.Char('Wellness Phone 3',
                                   help='Third Wellness phone of contact')
    geolocator_cordinates = fields.Char('GeoLocator Coordinates', help='GeoLocator Coordinates of contact')
    days_visited = fields.Char('Days Visited', help='Days Visited')
    average_time_spent = fields.Char('Average Time Spent (Minutes)', help='Average Time Spent (Minutes)')
    number_of_chats = fields.Char('Number Of Chats', help='Number Of Chats')


    # Fields derived from the headers
    most_recent_visit = fields.Datetime('Most Recent Visit')
    first_visit = fields.Datetime('First Visit')
    first_page_visited = fields.Char('First Page Visited')
    referrer = fields.Char('Referrer')
    install_status = fields.Char('Install Status')
    installation_notes = fields.Text('Installation Notes')
    install_date_time = fields.Datetime('Install Date and Time')
    market = fields.Char('Market')
    sent_referral_email = fields.Char('Sent Referral Email')
    preferred_install_date = fields.Date('Preferred Install Date')
    installation_date = fields.Datetime('Installation Date')
    where_did_you_hear_about_us = fields.Char(
        'Where Did You Hear About Us?')
    unsubscribed_mode = fields.Char('Unsubscribed Mode')
    unsubscribed_time = fields.Datetime('Unsubscribed Time')
    original_lead_source = fields.Char('Original Lead Source')
    payment_received = fields.Char('Payment Received')
    products_purchased = fields.Text('Products Purchased')
    county = fields.Char('County')
    name_title = fields.Char('Title of Contact in Zoho')
    remote_ip_address = fields.Char('Remote IP Address')
    district_name = fields.Char('District Name')
    home_depot_store = fields.Char('HOME DEPOT STORE')
    deal_source = fields.Char('Deal source')
    coupon_code = fields.Char('Coupon Code')
    doing_business_as = fields.Char('Doing Business As',help='Doing Business As')
    usdot_number = fields.Char('USDOT Number',help='USDOT Number')
    tractors_count = fields.Char('Number of Tractors',help='Number of Tractors')
    truck_count = fields.Char('Number of Trucks',help='Number of Trucks')
    trailer_count = fields.Char('Number of Trailers',help='Number of Trailers')
    total_truck_count = fields.Char('Total Number of Trucks',help='Total Number of Trucks')
    total_power_units = fields.Char('Total Number of Power Units',help='Total Number of Power Units')
    fleet_size_code = fields.Char('Fleet Size Code',help='Fleet Size Code')
    total_trucks = fields.Char('Total trucks',help='Total trucks')
    rep1_name = fields.Char('Rep 1 - Full Name',help='Rep 1 - Full Name')
    rep2_name = fields.Char('Rep 2 - Full Name',help='Rep 2 - Last Name')
    territory = fields.Char('Territory', help='Territory')
    company_name = fields.Char('Company of Contact', help='Company of Contact')
    annual_truck_miles = fields.Char('Annual Miles Per Truck',help='Annual Miles Per Truck')
    percentage_miles_on_highway =  fields.Char('% of Miles on Highway',help='% of Miles on Highway')
    annual_foil_savings = fields.Char('Annual Per Foil Savings',help='Annual Per Foil Savings')
    fuel_cost_gallon = fields.Char('Fuel Cost Per Gallon',help='Fuel Cost Per Gallon')
    five_year_total_savings = fields.Char('5 Year Total Savings',help='5 Year Total Savings')
    miles_per_gallon = fields.Char('Miles Per Gallon',help='Miles Per Gallon')
    return_call_date = fields.Char('Return Call Date & Time',help='Return Call Date & Time')
    average_mpg = fields.Char('Average MPG',help='Average MPG')
    total_tractors = fields.Char('Total Tractors',help='Total Tractors')
    total_vans = fields.Char('Total Vans/Reefers',help='Total Vans/Reefers')
    average_miles_per_gallon = fields.Char('Average Miles Per Gallon',help='Average Miles Per Gallon')
    total_annual_miles_per_truck = fields.Char('Total Annual Miles Per Truck',help='Total Annual Miles Per Truck')
    primary_contact_first_name = fields.Char('Primary contact First Name', help='Primary contact First Name')
    primary_contact_second_name = fields.Char('Primary Contact Last Name', help='Primary Contact Last Name')
