from odoo import fields, models


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    zoho_reference = fields.Char('Zoho Quotation Id', help="Zoho record reference")
    quote_number = fields.Char('Quotes Number', help="Quotes Number")
    subject = fields.Char('Subject', help="Subject")
    valid_date = fields.Date('Valid Until', help="Valid Until")
    carrier = fields.Char('Carrier', help="Carrier")
    billing_street = fields.Char('Billing Street', help="Billing Street")
    shipping_street = fields.Char('Shipping Street', help="Shipping Street")
    billing_city = fields.Char('Billing City', help="Billing City")
    shipping_city = fields.Char('Shipping City', help="Shipping City")
    billing_state = fields.Many2one('res.country.state','Billing State', help="Shipping City")
    shipping_state = fields.Many2one('res.country.state','Shipping State', help="Shipping City")
    billing_code = fields.Char('Billing Code', help="Billing Code")
    shipping_code = fields.Char('Shipping Code', help="Billing Code")
    zoho_terms = fields.Text('Terms and Conditions',help='Terms and Conditions')
    zoho_description = fields.Text('Description of zoho',help='Description')
    delivered = fields.Char('DELIVERED',help='DELIVERED')
    installed = fields.Char('Installed',help='Installed')
    roof_length = fields.Char('Roof Length',help='Roof Length')
    roof_height = fields.Char('Roof Height',help='Roof Height')
    gauge = fields.Char('Gauge',help='Gauge')
    roof_color = fields.Char('Roof Color', help='Roof Color')
    roof_width = fields.Char('Roof Width', help='Roof Width')
    pitch = fields.Char('Pitch', help='Pitch')
    permit = fields.Char('Permit', help='Permit')
    turn_key = fields.Char('GC or Turn Key',help='GC or Turn Key')
    power_source_quoted = fields.Char('Power Source Quoted?', help='Power Source Quoted?')
    terms = fields.Char('Terms', help='Terms')
    sales_rep = fields.Char('Sales Representative', help='Sales Representative')
    install_date = fields.Date('Expected Delivery/Install Date', help='Expected Delivery/Install Date')
    contract_date = fields.Date('Contract Sign Date', help='Contract Sign Date')
    payment_terms = fields.Char('Payment Terms in Zoho', help='Payment Terms')
    enclosed_gables = fields.Char('Enclosed Gables?', help='Enclosed Gables?')
    engineering_needed = fields.Char('Engineering Needed?', help='Engineering Needed?')
    wall_color = fields.Char('Trim/Wall Color', help='Trim/Wall Color')
    terms2 = fields.Char('Terms2',help='Terms2')
    job_number = fields.Char('Job Number - MT', help='Job Number - MT')
    product_family = fields.Char('Product Family', help='Product Family')
    submit_to_erp = fields.Char('Submit to ERP?',help='Submit to ERP?')
    bix_box_retailer_sale = fields.Char('Bix Box Retailer Sale', help='Bix Box Retailer Sale')
    amount_of_deposit =  fields.Char('Amount of Deposit', help='Amount of Deposit')
    deposit_taken = fields.Char('Deposit Taken',help='Deposit Taken')
    internal_notes = fields.Text('Internal Notes', help='Internal Notes')


